steps:
  # - command: "sudo systemctl start docker"
  #   label: "Start Docker Service"

  - label: "🤡 :hammer:"
    plugins:
      - plugin-tester#v1.0.0: ~
        command: "systemctl start docker"

  - label: ":sparkles: lint"
    plugins:
      - plugin-linter#v3.1.0:
          id: detect-clowns

  - label: ":shell: Shellcheck"
    plugins:
      - shellcheck#v1.3.0:
          files: hooks/**
