steps:

  - label: "Set Buildkite Git commit metadata"
    command: |
      buildkite-agent meta-data exists buildkite:git:commit
      buildkite-agent meta-data set buildkite:git:commit < /dev/stdin
      
  - plugins:
      - detect-clowns#v2.0.0: ~
    command: |
      echo "Running the plugin-tester plugin"
  - label: "🤡 :hammer:"
    plugins:
      - plugin-tester#v1.0.0: ~

  - label: ":sparkles: lint"
    plugins:
      - plugin-linter#v3.1.0:
          id: detect-clowns

  - label: ":shell: Shellcheck"
    plugins:
      - shellcheck#v1.3.0:
          files: hooks/**
