steps:
  - command: echo "Hello, world!"
  - label: "🤡 :hammer:"
    plugins:
      - plugin-tester#v1.0.0: ~
        command: ./hooks/command.sh

  - label: ":sparkles: lint"
    plugins:
      - plugin-linter#v3.1.0:
          id: detect-clowns

  - label: ":shell: Shellcheck"
    plugins:
      - shellcheck#v1.3.0:
          files: hooks/**
